package network

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerateSwarmKey_WritesValidPSKFile verifies the happy path: a key
// generated by GenerateSwarmKey has the libp2p-mandated PSK header, a 64-char
// hex section (32 bytes * 2), and is written with mode 0600 so it can't be
// read by other users on shared machines.
func TestGenerateSwarmKey_WritesValidPSKFile(t *testing.T) {
	t.Parallel()

	keyPath := filepath.Join(t.TempDir(), "swarm.key")
	if err := GenerateSwarmKey(keyPath); err != nil {
		t.Fatalf("GenerateSwarmKey: %v", err)
	}

	raw, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatalf("read key: %v", err)
	}

	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	if len(lines) != 3 {
		t.Fatalf("expected 3 lines, got %d: %q", len(lines), string(raw))
	}

	// The libp2p pnet spec requires these exact first two lines.
	if lines[0] != "/key/swarm/psk/1.0.0/" {
		t.Errorf("wrong header line 1: %q", lines[0])
	}
	if lines[1] != "/base16/" {
		t.Errorf("wrong header line 2: %q", lines[1])
	}
	// 32 bytes of entropy → 64 hex chars.
	if len(lines[2]) != 64 {
		t.Errorf("hex body wrong length: got %d, want 64", len(lines[2]))
	}

	// Verify file mode is locked down. We mask against 0777 because some
	// test environments add sticky/setuid bits we don't care about.
	info, err := os.Stat(keyPath)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Errorf("file mode = %o, want 0600", perm)
	}
}

// TestGenerateSwarmKey_UnwritablePath verifies we return a wrapped error
// instead of silently swallowing I/O failures — the kind of bug that would
// otherwise let a user think they had a persisted key when they didn't.
func TestGenerateSwarmKey_UnwritablePath(t *testing.T) {
	t.Parallel()

	// Nested path where the parent dir doesn't exist → os.WriteFile fails.
	keyPath := filepath.Join(t.TempDir(), "does-not-exist", "swarm.key")
	err := GenerateSwarmKey(keyPath)
	if err == nil {
		t.Fatal("expected error for unwritable path, got nil")
	}
	if !strings.Contains(err.Error(), "write swarm key file") {
		t.Errorf("expected wrapped 'write swarm key file' error, got: %v", err)
	}
}

// TestLoadSwarmKey_RoundTrip generates N keys and verifies each loads back to
// the same PSK bytes. Guards against subtle RNG/encoding bugs that would only
// show up on certain random seeds.
func TestLoadSwarmKey_RoundTrip(t *testing.T) {
	t.Parallel()

	const iterations = 5
	for i := 0; i < iterations; i++ {
		keyPath := filepath.Join(t.TempDir(), "swarm.key")
		if err := GenerateSwarmKey(keyPath); err != nil {
			t.Fatalf("generate[%d]: %v", i, err)
		}

		psk1, err := LoadSwarmKey(keyPath)
		if err != nil {
			t.Fatalf("load1[%d]: %v", i, err)
		}
		psk2, err := LoadSwarmKey(keyPath)
		if err != nil {
			t.Fatalf("load2[%d]: %v", i, err)
		}

		// pnet.PSK is a []byte-backed type; bytes.Equal is the canonical comparison.
		if !bytes.Equal(psk1, psk2) {
			t.Errorf("iteration %d: two loads produced different PSKs", i)
		}
		if len(psk1) != 32 {
			t.Errorf("iteration %d: PSK length = %d, want 32", i, len(psk1))
		}
	}
}

// TestLoadSwarmKey_Errors covers the four ways a key file can be malformed.
// Each row represents a distinct corruption scenario an operator might hit in
// the wild (wrong format tool, partial download, empty file, bad hex).
func TestLoadSwarmKey_Errors(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name       string
		contents   string
		wantSubstr string
		writeFile  bool // if false, don't create the file (tests missing-file path)
	}{
		{
			name:       "missing file",
			writeFile:  false,
			wantSubstr: "could not open swarm key file",
		},
		{
			name:       "empty file",
			writeFile:  true,
			contents:   "",
			wantSubstr: "could not decode swarm key",
		},
		{
			name:       "wrong header",
			writeFile:  true,
			contents:   "/key/wrong/format/\n/base16/\n" + strings.Repeat("a", 64) + "\n",
			wantSubstr: "could not decode swarm key",
		},
		{
			name:       "truncated hex",
			writeFile:  true,
			contents:   "/key/swarm/psk/1.0.0/\n/base16/\nabc\n",
			wantSubstr: "could not decode swarm key",
		},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			keyPath := filepath.Join(t.TempDir(), "swarm.key")
			if tc.writeFile {
				if err := os.WriteFile(keyPath, []byte(tc.contents), 0o600); err != nil {
					t.Fatalf("write fixture: %v", err)
				}
			}

			_, err := LoadSwarmKey(keyPath)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
			if !strings.Contains(err.Error(), tc.wantSubstr) {
				t.Errorf("error %q does not contain %q", err.Error(), tc.wantSubstr)
			}
		})
	}
}
