package merkle

import "fmt"

// InclusionProof returns the RFC 6962 audit path for the leaf at idx
// against the tree's current state. The returned slice contains the
// sibling hashes from the leaf level up to (but not including) the
// root, in bottom-up order — exactly the order VerifyInclusion
// consumes them.
//
// Errors:
//
//   - ErrIndexOutOfRange if idx >= Size().
//   - ErrEmptyTree if Size() == 0.
func (t *Tree) InclusionProof(idx uint64) ([][32]byte, error) {
	n := uint64(len(t.leaves))
	if n == 0 {
		return nil, ErrEmptyTree
	}
	if idx >= n {
		return nil, fmt.Errorf("%w: idx=%d size=%d", ErrIndexOutOfRange, idx, n)
	}
	return path(idx, t.leaves), nil
}

// path implements the RFC 6962 §2.1.1 PATH algorithm:
//
//	PATH(m, D[n]) = []                                            // n == 1
//	PATH(m, D[n]) = PATH(m,   D[0:k])  :: MTH(D[k:n])             // m < k
//	PATH(m, D[n]) = PATH(m-k, D[k:n])  :: MTH(D[0:k])             // m >= k
//
// The returned slice grows from leaf-level siblings upward.
func path(m uint64, leaves [][32]byte) [][32]byte {
	n := uint64(len(leaves))
	if n == 1 {
		return nil
	}
	k := largestPowerOfTwoLessThan(n)
	if m < k {
		return append(path(m, leaves[:k]), computeRoot(leaves[k:]))
	}
	return append(path(m-k, leaves[k:]), computeRoot(leaves[:k]))
}

// VerifyInclusion validates that leafHash sits at position idx in a
// tree of size size whose root is root, using the supplied audit
// proof. Standalone (no Tree required) so other peers can verify
// proofs they receive over the network.
//
// The function returns false on any inconsistency: short proof,
// long proof, wrong-shape proof, mismatched root, mismatched leaf,
// index out of range. It MUST NOT panic on bad input — proofs
// arrive over libp2p from peers who may be hostile.
//
// SECURITY BOUNDARY: an RFC 6962 inclusion proof binds (leafHash, idx,
// size, root). Callers MUST pass `size` and `root` from a trusted
// signed LogHead — if the caller's `size` differs from the size the
// proof was generated under but the recursion shape happens to match
// (e.g. size 50 vs 51 for idx 7 both split at k=32), the verifier
// cannot distinguish the two from the proof alone. The signed LogHead
// pairs (root, size) together so this attack is moot in practice; just
// never let an untrusted source override the size.
func VerifyInclusion(leafHash [32]byte, idx uint64, size uint64, root [32]byte, proof [][32]byte) bool {
	if size == 0 || idx >= size {
		return false
	}
	derived, consumed, ok := rebuildRoot(leafHash, idx, size, proof, 0)
	if !ok {
		return false
	}
	// Any unconsumed sibling means the proof was longer than the tree
	// shape allows for this (idx, size) — reject as malformed.
	if consumed != len(proof) {
		return false
	}
	return derived == root
}

// ConsistencyProof returns the RFC 6962 §2.1.2 PROOF that the tree's
// current state extends the older snapshot defined by oldSize. The
// returned slice contains the hashes a verifier needs to derive both
// the old root and the current root and confirm they are consistent
// — i.e. that the current tree was produced by appending only.
//
// Errors:
//
//   - ErrConsistencyOutOfRange if oldSize == 0, oldSize > Size().
//
// Used by P2-5 inclusion-proof handling and by witnesses doing
// strict-extension verification (P2-2's "head.TreeSize must extend
// the previous head" check upgrades to "the new root must be a
// consistent extension of the previous root" via this proof).
func (t *Tree) ConsistencyProof(oldSize uint64) ([][32]byte, error) {
	newSize := uint64(len(t.leaves))
	if oldSize == 0 || oldSize > newSize {
		return nil, fmt.Errorf("%w: old=%d new=%d", ErrConsistencyOutOfRange, oldSize, newSize)
	}
	if oldSize == newSize {
		return nil, nil // trees identical; empty proof
	}
	return consistencyProof(oldSize, t.leaves, true), nil
}

// consistencyProof implements RFC 6962 §2.1.4 PROOF. The boolean
// `complete` tracks whether m is the size of a tree we descended into
// from the right; this flips after the first right-recursion to
// match the spec's `b` flag.
func consistencyProof(m uint64, leaves [][32]byte, complete bool) [][32]byte {
	n := uint64(len(leaves))
	if m == n {
		if complete {
			return nil
		}
		return [][32]byte{computeRoot(leaves)}
	}
	k := largestPowerOfTwoLessThan(n)
	if m <= k {
		sub := consistencyProof(m, leaves[:k], complete)
		return append(sub, computeRoot(leaves[k:]))
	}
	sub := consistencyProof(m-k, leaves[k:], false)
	return append(sub, computeRoot(leaves[:k]))
}

// VerifyConsistency reports whether proof shows that an oldRoot at
// oldSize extends to newRoot at newSize via append-only growth. The
// proof must have been generated by ConsistencyProof on a tree whose
// state matches (oldSize, oldRoot, newSize, newRoot). Returns false
// on any mismatch — including a structurally-correct proof against
// the wrong roots.
//
// Algorithm: RFC 6962 §2.1.4 inverse — recursively fold the proof to
// derive the old root and the new root separately and check both
// match. The oldRoot is threaded through the recursion as the
// "context" hash the prover omitted when its `complete` flag was true
// at the base case.
func VerifyConsistency(oldSize, newSize uint64, oldRoot, newRoot [32]byte, proof [][32]byte) bool {
	if oldSize == 0 || oldSize > newSize {
		return false
	}
	if oldSize == newSize {
		return len(proof) == 0 && oldRoot == newRoot
	}
	derivedOld, derivedNew, ok := foldConsistency(oldSize, newSize, proof, oldRoot, true)
	if !ok {
		return false
	}
	return derivedOld == oldRoot && derivedNew == newRoot
}

// foldConsistency mirrors consistencyProof: walks the same (m, n)
// recursion top-down, consumes proof entries from the tail in the
// order they were appended, and returns the derived (oldRoot,
// newRoot, ok).
//
// The `complete` boolean tracks the same `b` flag as the prover. When
// `complete=true` at the base case (m == n), the prover omitted the
// m-prefix hash because the verifier already has it — that's the
// `oldRootCtx` parameter, threaded through unchanged.
func foldConsistency(m, n uint64, proof [][32]byte, oldRootCtx [32]byte, complete bool) ([32]byte, [32]byte, bool) {
	if m == n {
		if complete {
			// Prover omitted the m-prefix hash; verifier supplies it
			// from the caller's known oldRoot. No proof entries
			// should be left at this base.
			if len(proof) != 0 {
				return [32]byte{}, [32]byte{}, false
			}
			return oldRootCtx, oldRootCtx, true
		}
		// Prover included the m-prefix hash explicitly as proof[0].
		if len(proof) != 1 {
			return [32]byte{}, [32]byte{}, false
		}
		return proof[0], proof[0], true
	}
	if len(proof) == 0 {
		return [32]byte{}, [32]byte{}, false
	}
	k := largestPowerOfTwoLessThan(n)
	last := proof[len(proof)-1]
	head := proof[:len(proof)-1]
	if m <= k {
		oldD, newD, ok := foldConsistency(m, k, head, oldRootCtx, complete)
		if !ok {
			return [32]byte{}, [32]byte{}, false
		}
		// The right subtree of the new tree (last) is appended.
		// The old tree had no right subtree of size n-k.
		return oldD, HashChildren(newD, last), true
	}
	// m > k: the OLD prefix straddles the split, so the left subtree
	// is shared between old and new — last == MTH(D[0:k]).
	oldD, newD, ok := foldConsistency(m-k, n-k, head, oldRootCtx, false)
	if !ok {
		return [32]byte{}, [32]byte{}, false
	}
	return HashChildren(last, oldD), HashChildren(last, newD), true
}

// rebuildRoot mirrors the recursive PATH algorithm used to generate the
// proof (see path()): it descends top-down, consumes sibling hashes
// from proof in the same order they were appended, and combines them
// in the correct (left, right) orientation as the recursion unwinds.
//
// Returns the derived root for the (idx, size) window, the number of
// proof entries consumed, and ok=false on under-supplied proof.
func rebuildRoot(leafHash [32]byte, idx uint64, size uint64, proof [][32]byte, cursor int) ([32]byte, int, bool) {
	if size == 1 {
		// Leaf level: no sibling, no hash combine.
		return leafHash, cursor, true
	}
	k := largestPowerOfTwoLessThan(size)
	if idx < k {
		sub, next, ok := rebuildRoot(leafHash, idx, k, proof, cursor)
		if !ok || next >= len(proof) {
			return [32]byte{}, 0, false
		}
		return HashChildren(sub, proof[next]), next + 1, true
	}
	sub, next, ok := rebuildRoot(leafHash, idx-k, size-k, proof, cursor)
	if !ok || next >= len(proof) {
		return [32]byte{}, 0, false
	}
	return HashChildren(proof[next], sub), next + 1, true
}
